In [1]:
import json
import logging
import sys
import numpy as np
import pandas as pd
import greengrasssdk
# Create random name
import random
import string

In [2]:
MAX_NUM_CARPORT = 100
PUBLIC_CARPORT = 80
# init as free
carport_array = np.zeros(MAX_NUM_CARPORT, dtype=np.int8)
next_free_array = (i+1 for i in range(MAX_NUM_CARPORT))
# next_private_free = 0
next_public_free = 0
num_occupied = 0

dataset = pd.DataFrame(
    columns=["vehicle_id", "user_id", "user_name", "veh_type", "veh_state", "registered_carport_id"])
# "veh_type": 1 registered, 2 temporary(guest)
# "veh_state": >=0: occupied carport id,
user_set = {}

In [48]:
def generate_user(id):
    if id not in user_set.keys():
        user_set[id] = ''.join(
            [random.choice(string.ascii_letters + string.digits) for n in range(4)])


def generate_vehicle(id):
    veh_dic = {}
    veh_dic["vehicle_id"] = ''.join(
        [random.choice(string.ascii_letters + string.digits) for n in range(5)])
    if id not in user_set.keys():
        generate_user(id)
    veh_dic["user_id"] = id
    veh_dic["user_name"] = user_set[id]
    veh_dic["veh_type"] = 1
    veh_dic["veh_state"] = -1
    veh_dic["registered_carport_id"] = random.choice(range(PUBLIC_CARPORT))
    return veh_dic

In [57]:
def assign_carport(type, veh_id):
    global num_occupied
    assign_id = 0
    if num_occupied >= MAX_NUM_CARPORT:
        return -1
    if type == 1:  # has registered carport
        filtered_df=dataset[dataset.vehicle_id == veh_id]
        # print(filtered_df)
        veh_dic={}
        veh_dic=filtered_df.to_dict(orient="list")
#         print(veh_dic)
        assign_id_list = veh_dic["registered_carport_id"]
        for assign_id in assign_id_list:
            if carport_array[assign_id] == 0:
                num_occupied += 1
                dataset.loc[dataset.vehicle_id == veh_id,"veh_state"] = assign_id
                return assign_id
    # not get the registered carport or guest car
    assign_id = next_public_free
    carport_array[next_public_free] = type  # assign to a guest car
    next_public_free = next_free_array[assign_id]
    num_occupied += 1
    dataset.loc[dataset.vehicle_id == veh_id,"veh_state"] = assign_id
    return assign_id


def unassign_carport(carport_id):
    global num_occupied
    if carport_array[carport_id] == 0:
        return -1
    if carport_id >= PUBLIC_CARPORT:
        next_free_array[carport_id] = next_public_free
        next_public_free = carport_id
    carport_array[carport_id] =0
    dataset.loc[dataset.carport_id == veh_id,"veh_state"]
    num_occupied -= 1
    return 0

In [58]:
# init data(10 vehicles)
dataset.drop(dataset.index, inplace=True)
for i in range(10):
    dic = generate_vehicle(i)
#     print(dic)
    dataset = dataset.append(dic, ignore_index=True)
#     print(dataset.head())
    assign_carport(1, dic["vehicle_id"])

In [59]:
dataset.head(10)

  vehicle_id user_id user_name veh_type veh_state registered_carport_id
0      wcwDN       0      UHJS        1        78                    78
1      weH99       1      hlIK        1         8                     8
2      6h471       2      HxiD        1         6                     6
3      48czG       3      Ey5Y        1        11                    11
4      z3hl1       4      88on        1        32                    32
5      5eimv       5      4M2j        1        18                    18
6      N9PJS       6      Rf7I        1        42                    42
7      sOnVI       7      axMd        1        72                    72
8      linKb       8      vJS3        1        44                    44
9      eeJvX       9      8CpQ        1        26                    26