In [1]:
import json
import logging
import sys
import numpy as np
import pandas as pd
import greengrasssdk
# Create random name
import random
import string

In [2]:
MAX_NUM_CARPORT = 100
PUBLIC_CARPORT = 80
# init as free
carport_array = np.zeros(MAX_NUM_CARPORT, dtype=np.int8)
next_free_array = [i+1 for i in range(PUBLIC_CARPORT,MAX_NUM_CARPORT)]
temporary_veh_dic = {}
next_public_free = PUBLIC_CARPORT
num_occupied = 0

dataset = pd.DataFrame(
    columns=["vehicle_id", "user_id", "user_name", "veh_type", "veh_state", "registered_carport_id"])
# "veh_type": 1 registered, 2 temporary(guest)
# "veh_state": >=0: occupied carport id,
user_set = {}

In [3]:
def generate_user(id):
    global user_set
    if id not in user_set.keys():
        user_set[id] = ''.join(
            [random.choice(string.ascii_letters + string.digits) for n in range(4)])


def generate_vehicle(id):
    global user_set
    veh_dic = {}
    veh_dic["vehicle_id"] = ''.join(
        [random.choice(string.ascii_letters + string.digits) for n in range(5)])
    if id not in user_set.keys():
        generate_user(id)
    veh_dic["user_id"] = id
    veh_dic["user_name"] = user_set[id]
    veh_dic["veh_type"] = 1
    veh_dic["veh_state"] = -1
    veh_dic["registered_carport_id"] = random.choice(range(PUBLIC_CARPORT))
    return veh_dic

def init_guest(veh_id):
    veh_dic = {}
    veh_dic["vehicle_id"] = veh_id
    veh_dic["user_id"] = -1
    veh_dic["user_name"] = "none"
    veh_dic["veh_type"] = 2
    veh_dic["veh_state"] = -1
    veh_dic["registered_carport_id"] = -1
    return veh_dic

def debug():
    global num_occupied, carport_array, next_free_array, next_public_free
    print("num_occupied", num_occupied)
    print("carport_array", carport_array)
    print("next_free_array", next_free_array)
    print("next_public_free", next_public_free)

In [4]:
def assign_carport(veh_type, veh_id):
    global num_occupied, carport_array, next_free_array, next_public_free, dataset
    assign_id = 0
    if num_occupied >= MAX_NUM_CARPORT:
        return -1
    if veh_type == 1:  # has registered carport
        filtered_df=dataset[dataset.vehicle_id == veh_id]
        # print(filtered_df)
        veh_dic={}
        veh_dic=filtered_df.to_dict(orient="list")
#         print(veh_dic)
        assign_id_list = veh_dic["registered_carport_id"]
        for assign_id in assign_id_list:
            if carport_array[assign_id] == 0:
                num_occupied += 1
                carport_array[assign_id]=1
                dataset.loc[dataset.vehicle_id == veh_id,"veh_state"] = assign_id
                return assign_id
    # not get the registered carport or guest car
    assign_id = next_public_free
    carport_array[next_public_free] = veh_type  # assign to a guest car
    next_public_free = next_free_array[assign_id-PUBLIC_CARPORT]
    num_occupied += 1
    dataset.loc[dataset.vehicle_id == veh_id,"veh_state"] = assign_id
    return assign_id


def unassign_carport(carport_id):
    global num_occupied, carport_array, next_free_array, next_public_free, dataset
    if carport_array[carport_id] == 0:
        return -1
    if carport_id >= PUBLIC_CARPORT:
        next_free_array[carport_id-PUBLIC_CARPORT] = next_public_free
        next_public_free = carport_id
    carport_array[carport_id] =0
    dataset.loc[dataset.veh_state == carport_id,"veh_state"]=-1
    num_occupied -= 1
    return 0

In [5]:
# init data(10 vehicles)
dataset.drop(dataset.index, inplace=True)
for i in range(10):
    dic = generate_vehicle(i)
#     print(dic)
    dataset = dataset.append(dic, ignore_index=True)
    assign_carport(1, dic["vehicle_id"])
#     print(dataset.head())

In [6]:
dataset.head(10)

  vehicle_id user_id user_name veh_type veh_state registered_carport_id
0      k2QWk       0      6wqL        1        59                    59
1      SMvp9       1      H3Zo        1        15                    15
2      bvku8       2      Vqcv        1        34                    34
3      Rmtio       3      23Vd        1        79                    79
4      K0cdf       4      2ZPI        1         9                     9
5      H5qCH       5      rWEx        1        52                    52
6      7l8bh       6      EJA9        1        49                    49
7      RMaGd       7      6mtA        1        45                    45
8      4wsN1       8      N5c6        1        61                    61
9      raawZ       9      u8Gs        1        27                    27

In [7]:
def lambda_handler(event):
    global carport_array, dataset
    # controller
    if event["device"] == "controller":
        message = {"device": "cloud",
                   "behavior": "re_enter", "detail": "none"}
        veh_id = event["detail"]
        filtered_df = dataset[dataset.vehicle_id == veh_id]
        if filtered_df.empty:
            dic = init_guest(veh_id)
#             print(dic)
            dataset = dataset.append(dic, ignore_index=True)
            filtered_df = dataset[dataset.vehicle_id == veh_id]

        veh_dic = {}
        veh_dic = filtered_df.to_dict(orient="dict")
        print(veh_dic)
        if list(veh_dic["veh_state"].values())[0] >= 0:
            # quit
            message["behavior"] = "re_quit"
            ret = unassign_carport(list(veh_dic["veh_state"].values())[0])
            if ret < 0:
                # error
                message["detail"] = "error"
            else:
                message["detail"] = str(unassign_carport(list(veh_dic["veh_state"].values())[0]))
                if list(veh_dic["veh_type"].values())[0] == 2:
                    dataset.drop(index=list(veh_dic["veh_state"].keys())[0], inplace=True)
                    return
        else:
            # enter
            assign_id = assign_carport(list(veh_dic["veh_type"].values())[0], veh_id)
            if assign_id < 0:
                # error
                message["detail"] = "error"
            else:
                message["detail"] = str(assign_id)

In [8]:
msg = {"device": "controller", "behavior": "enter", "detail": "aefr"}
lambda_handler (msg)
debug()
dataset.head(20)

{'vehicle_id': {10: 'aefr'}, 'user_id': {10: -1}, 'user_name': {10: 'none'}, 'veh_type': {10: 2}, 'veh_state': {10: -1}, 'registered_carport_id': {10: -1}}
num_occupied 11
carport_array [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next_free_array [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
next_public_free 81

   vehicle_id user_id user_name veh_type veh_state registered_carport_id
0       k2QWk       0      6wqL        1        59                    59
1       SMvp9       1      H3Zo        1        15                    15
2       bvku8       2      Vqcv        1        34                    34
3       Rmtio       3      23Vd        1        79                    79
4       K0cdf       4      2ZPI        1         9                     9
5       H5qCH       5      rWEx        1        52                    52
6       7l8bh       6      EJA9        1        49                    49
7       RMaGd       7      6mtA        1        45                    45
8       4wsN1       8      N5c6        1        61                    61
9       raawZ       9      u8Gs        1        27                    27
10       aefr      -1      none        2        80                    -1

In [10]:
lambda_handler (msg)
debug()
dataset.head(20)

{'vehicle_id': {10: 'aefr'}, 'user_id': {10: -1}, 'user_name': {10: 'none'}, 'veh_type': {10: 2}, 'veh_state': {10: 80}, 'registered_carport_id': {10: -1}}

num_occupied 10
carport_array [0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next_free_array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
next_public_free 80